

EXPORT_ENV=SYSAPP_INSTALL_PATH=$(SYSAPP_INSTALL_PATH) \
	   USRAPP_INSTALL_PATH=$(USRAPP_INSTALL_PATH) \
	   LIBRARY_INSTALL_PATH=$(LIBRARY_INSTALL_PATH) \
           FIRMWARE_INSTALL_PATH=$(FIRMWARE_INSTALL_PATH) \
	   IMAGE_INSTALL_PATH=$(BINARIES_DIR) \
           TOOLS_INSTALL_PATH=$(TOOLS_INSTALL_PATH) \
           CROSS_COMPILE=$(TARGET_CROSS) \
           SDK_INSTALL_PATH=$(SDK_PATH) \
	   SDK_INSTALL_USER_PATH=$(SDK_USER_PATH) \
		   SYSTEM_PATH=$(SYSTEM_DIR) \
		   RECOVERY_DIR=$(RECOVERY_DIR) \
		   FIRMWARE_PCI_COMPLY=$(FIRMWARE_PCI_COMPLY) \
		   PREBUILT_PACKAGE_URL=$(BR2_PREBUILT_PACKAGE_URL) \
		   SCRIPT_PATH=$(TOPDIR)/support/scripts \
		   SIGNATURE="$(TOPDIR)/support/scripts/signature -c $(call qstrip,$(BR2_MF_SIGNATURE_IP)):$(call qstrip,$(BR2_MF_SIGNATURE_PORT))" \
		   SIGNATURE_V2="$(SIGNATURE_V2)" \
		   NDK_CFLAGS=$(NDK_CFLAGS) \
		NDK_BUILD_FLAGS="-j$(PARALLEL_JOBS)"
